"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from deepset_cloud import utils
from enum import Enum
from typing import Optional

class TypeOfTheNotebookServer(str, Enum):
    r"""Use 'gpu-server' to start a GPU instance, use 'cpu-server' to start a CPU instance."""
    CPU_SERVER = 'cpu-server'
    GPU_SERVER = 'gpu-server'
    UNKNOWN = 'unknown'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class NotebookServerPost:
    server_type: Optional[TypeOfTheNotebookServer] = dataclasses.field(default=TypeOfTheNotebookServer.GPU_SERVER, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('server_type'), 'exclude': lambda f: f is None }})
    r"""Use 'gpu-server' to start a GPU instance, use 'cpu-server' to start a CPU instance."""
    

