"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from .api_token import APIToken
from .document_store import DocumentStore
from .eval_run import EvalRun
from .evaluation_set import EvaluationSet
from .file import File
from .health import Health
from .model_registry_token import ModelRegistryToken
from .models_ import Models
from .notebook import Notebook
from .organization import Organization
from .pipeline import Pipeline
from .sdkconfiguration import SDKConfiguration
from .search_session import SearchSession
from .shared_prototype import SharedPrototype
from .upload_session import UploadSession
from .user import User
from .workspace import Workspace
from deepset_cloud import utils

class DeepsetCloud:
    r"""Deepset Cloud: deepset Cloud API description"""
    api_token: APIToken
    document_store: DocumentStore
    eval_run: EvalRun
    evaluation_set: EvaluationSet
    file: File
    health: Health
    model_registry_token: ModelRegistryToken
    models: Models
    notebook: Notebook
    organization: Organization
    pipeline: Pipeline
    search_session: SearchSession
    shared_prototype: SharedPrototype
    upload_session: UploadSession
    user: User
    workspace: Workspace

    sdk_configuration: SDKConfiguration

    def __init__(self,
                 server_idx: int = None,
                 server_url: str = None,
                 url_params: dict[str, str] = None,
                 client: requests_http.Session = None,
                 retry_config: utils.RetryConfig = None
                 ) -> None:
        """Instantiates the SDK configuring it with the provided parameters.
        
        :param server_idx: The index of the server to use for all operations
        :type server_idx: int
        :param server_url: The server URL to use for all operations
        :type server_url: str
        :param url_params: Parameters to optionally template the server URL with
        :type url_params: dict[str, str]
        :param client: The requests.Session HTTP client to use for all operations
        :type client: requests_http.Session
        :param retry_config: The utils.RetryConfig to use globally
        :type retry_config: utils.RetryConfig
        """
        if client is None:
            client = requests_http.Session()
        
        security_client = client
        
        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        self.sdk_configuration = SDKConfiguration(client, security_client, server_url, server_idx, retry_config=retry_config)
       
        self._init_sdks()
    
    def _init_sdks(self):
        self.api_token = APIToken(self.sdk_configuration)
        self.document_store = DocumentStore(self.sdk_configuration)
        self.eval_run = EvalRun(self.sdk_configuration)
        self.evaluation_set = EvaluationSet(self.sdk_configuration)
        self.file = File(self.sdk_configuration)
        self.health = Health(self.sdk_configuration)
        self.model_registry_token = ModelRegistryToken(self.sdk_configuration)
        self.models = Models(self.sdk_configuration)
        self.notebook = Notebook(self.sdk_configuration)
        self.organization = Organization(self.sdk_configuration)
        self.pipeline = Pipeline(self.sdk_configuration)
        self.search_session = SearchSession(self.sdk_configuration)
        self.shared_prototype = SharedPrototype(self.sdk_configuration)
        self.upload_session = UploadSession(self.sdk_configuration)
        self.user = User(self.sdk_configuration)
        self.workspace = Workspace(self.sdk_configuration)
    