"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from deepsetcloud import utils
from enum import Enum
from typing import Optional

class CloseSessionSessionCloseStatusEnumEnum(str, Enum):
    r"""An enumeration."""
    CLOSED = 'closed'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CloseSession:
    
    status: Optional[CloseSessionSessionCloseStatusEnumEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is None }})
    r"""Closes the session and starts the ingestion of the uploaded files."""
    