"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from deepsetcloud import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TagWithMeta:
    
    is_used_by_experiments: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_used_by_experiments') }})
    r"""Indicates if there are experiments that use this tag."""
    is_used_by_feedback: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_used_by_feedback') }})
    r"""Indicates if there are feedback items that use this tag."""
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    r"""Name of the tag"""
    tag_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tag_id') }})
    r"""Unique identifier of the tag"""
    