"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deepsetclouddocument as shared_deepsetclouddocument
from ..shared import httpvalidationerror as shared_httpvalidationerror
from typing import Optional


@dataclasses.dataclass
class GetAllDocumentsAPIV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsGetSecurity:
    
    http_bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class GetAllDocumentsAPIV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsGetRequest:
    
    index_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'index_name', 'style': 'simple', 'explode': False }})
    r"""The name of the pipeline used to process the documents."""
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    return_embedding: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'return_embedding', 'style': 'form', 'explode': True }})
    

@dataclasses.dataclass
class GetAllDocumentsAPIV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsGetResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    deepset_cloud_documents: Optional[list[shared_deepsetclouddocument.DeepsetCloudDocument]] = dataclasses.field(default=None)
    r"""Successful Response"""
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    