"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import searchsessionpostresponse as components_searchsessionpostresponse
from typing import Optional


@dataclasses.dataclass
class CreateSearchSessionAPIV1WorkspacesWorkspaceNameSearchSessionsPostRequest:
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    



@dataclasses.dataclass
class CreateSearchSessionAPIV1WorkspacesWorkspaceNameSearchSessionsPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    search_session_post_response: Optional[components_searchsessionpostresponse.SearchSessionPostResponse] = dataclasses.field(default=None)
    r"""Successful Response"""
    

