"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import httpvalidationerror as shared_httpvalidationerror
from ..shared import postsharedprototype as shared_postsharedprototype
from ..shared import sharedprototype as shared_sharedprototype
from typing import Optional



@dataclasses.dataclass
class CreatePrototypeAPIV1WorkspacesWorkspaceNameSharedPrototypesPostRequest:
    post_shared_prototype: shared_postsharedprototype.PostSharedPrototype = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    




@dataclasses.dataclass
class CreatePrototypeAPIV1WorkspacesWorkspaceNameSharedPrototypesPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    shared_prototype: Optional[shared_sharedprototype.SharedPrototype] = dataclasses.field(default=None)
    r"""Successful Response"""
    

