"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import httpvalidationerror as shared_httpvalidationerror
from typing import Any, Optional



@dataclasses.dataclass
class DeleteUserAPIV1UsersUserIDDeleteSecurity:
    http_bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    




@dataclasses.dataclass
class DeleteUserAPIV1UsersUserIDDeleteRequest:
    user_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': False }})
    r"""A unique identifier of the user. You can obtain it by running the Get Users endpoint."""
    




@dataclasses.dataclass
class DeleteUserAPIV1UsersUserIDDeleteResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_user_api_v1_users_user_id_delete_200_application_json_any: Optional[Any] = dataclasses.field(default=None)
    r"""Successful Response"""
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

