"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from deepset_cloud import utils
from typing import Any, List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeleteFilesAPIV1WorkspacesWorkspaceNameFilesDeleteFiles:
    r"""Type the names of the files you want to delete, separated with commas."""
    names: List[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('names') }})
    r"""The names of the files to delete."""
    



@dataclasses.dataclass
class DeleteFilesAPIV1WorkspacesWorkspaceNameFilesDeleteRequest:
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    request_body: Optional[DeleteFilesAPIV1WorkspacesWorkspaceNameFilesDeleteFiles] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class DeleteFilesAPIV1WorkspacesWorkspaceNameFilesDeleteResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    any: Optional[Any] = dataclasses.field(default=None)
    r"""Successful Response"""
    

