"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import sessiondetail as components_sessiondetail
from typing import Optional


@dataclasses.dataclass
class GetSessionStatusAPIV1WorkspacesWorkspaceNameUploadSessionsSessionIDGetRequest:
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the session."""
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    



@dataclasses.dataclass
class GetSessionStatusAPIV1WorkspacesWorkspaceNameUploadSessionsSessionIDGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    session_detail: Optional[components_sessiondetail.SessionDetail] = dataclasses.field(default=None)
    r"""Your upload sessions."""
    

