"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import httpvalidationerror as shared_httpvalidationerror
from ..shared import workspacestats as shared_workspacestats
from typing import Optional



@dataclasses.dataclass
class GetWorkspaceStatsAPIV1WorkspacesWorkspaceNameStatsGetRequest:
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    




@dataclasses.dataclass
class GetWorkspaceStatsAPIV1WorkspacesWorkspaceNameStatsGetResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    workspace_stats: Optional[shared_workspacestats.WorkspaceStats] = dataclasses.field(default=None)
    r"""Successful Response"""
    

