"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import pipelineindexing as components_pipelineindexing
from typing import Optional


@dataclasses.dataclass
class GetPipelineAPIV1WorkspacesWorkspaceNamePipelinesPipelineNameGetRequest:
    pipeline_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'pipeline_name', 'style': 'simple', 'explode': False }})
    r"""The name of the pipeline you want to fetch."""
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    



@dataclasses.dataclass
class GetPipelineAPIV1WorkspacesWorkspaceNamePipelinesPipelineNameGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    pipeline_indexing: Optional[components_pipelineindexing.PipelineIndexing] = dataclasses.field(default=None)
    r"""Successful Response"""
    

