"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import httpvalidationerror as shared_httpvalidationerror
from typing import Optional



@dataclasses.dataclass
class GetFileMetaAPIV1WorkspacesWorkspaceNameFilesFileIDMetaGetRequest:
    file_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'file_id', 'style': 'simple', 'explode': False }})
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    




@dataclasses.dataclass
class GetFileMetaAPIV1WorkspacesWorkspaceNameFilesFileIDMetaGetResponseGetFileMetaAPIV1WorkspacesWorkspaceNameFilesFileIDMetaGet:
    r"""Successful Response"""
    




@dataclasses.dataclass
class GetFileMetaAPIV1WorkspacesWorkspaceNameFilesFileIDMetaGetResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    response_get_file_meta_api_v1_workspaces_workspace_name_files_file_id_meta_get: Optional[GetFileMetaAPIV1WorkspacesWorkspaceNameFilesFileIDMetaGetResponseGetFileMetaAPIV1WorkspacesWorkspaceNameFilesFileIDMetaGet] = dataclasses.field(default=None)
    r"""Successful Response"""
    

