"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import workspacestats as components_workspacestats
from typing import Optional


@dataclasses.dataclass
class GetWorkspaceStatsAPIV1WorkspacesWorkspaceNameStatsGetRequest:
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    



@dataclasses.dataclass
class GetWorkspaceStatsAPIV1WorkspacesWorkspaceNameStatsGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    workspace_stats: Optional[components_workspacestats.WorkspaceStats] = dataclasses.field(default=None)
    r"""Successful Response"""
    

