"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import rolestodb as components_rolestodb
from dataclasses_json import Undefined, dataclass_json
from deepset_cloud import utils
from typing import Any, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class InviteUserToOrganizationAPIV1OrganizationOrganizationIDInvitationPostInvitationRequest:
    r"""The definition of the user that you want to invite to the organization."""
    email: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('email') }})
    r"""Email of a user"""
    family_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('family_name') }})
    r"""Family name of a user"""
    given_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('given_name') }})
    r"""Given name of a user"""
    role: components_rolestodb.RolesToDB = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('role') }})
    r"""An enumeration."""
    



@dataclasses.dataclass
class InviteUserToOrganizationAPIV1OrganizationOrganizationIDInvitationPostRequest:
    request_body: InviteUserToOrganizationAPIV1OrganizationOrganizationIDInvitationPostInvitationRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    organization_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'organization_id', 'style': 'simple', 'explode': False }})
    r"""A unique identifier of the organization. You can obtain it from Get Organization."""
    



@dataclasses.dataclass
class InviteUserToOrganizationAPIV1OrganizationOrganizationIDInvitationPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    any: Optional[Any] = dataclasses.field(default=None)
    r"""Successful Response"""
    

