"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import workspace as shared_workspace
from typing import Optional



@dataclasses.dataclass
class ListWorkspacesAPIV1WorkspacesGetResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    workspace_list: Optional[list[shared_workspace.Workspace]] = dataclasses.field(default=None)
    r"""Successful Response"""
    

