"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import emptyclass as components_emptyclass
from ...models.components import notebook as components_notebook
from typing import Optional


@dataclasses.dataclass
class PostNotebookAPIV1NotebookPostRequest:
    empty_class: Optional[components_emptyclass.EmptyClass] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    pipeline_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'pipeline_id', 'style': 'form', 'explode': True }})
    r"""A unique identifier of a pipeline. You can obtain it from the List Pipelines endpoint."""
    



@dataclasses.dataclass
class PostNotebookAPIV1NotebookPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    notebook: Optional[components_notebook.Notebook] = dataclasses.field(default=None)
    r"""Successful Response"""
    

