"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import deepsetclouddocument as components_deepsetclouddocument
from ...models.components import querydocumentsparams as components_querydocumentsparams
from typing import List, Optional


@dataclasses.dataclass
class QueryDocumentsStreamAPIV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsQueryPostRequest:
    index_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'index_name', 'style': 'simple', 'explode': False }})
    r"""The name of the pipeline."""
    query_documents_params: components_querydocumentsparams.QueryDocumentsParams = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    



@dataclasses.dataclass
class QueryDocumentsStreamAPIV1WorkspacesWorkspaceNameIndexesIndexNameDocumentsQueryPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    response_query_documents_stream_api_v1_workspaces_workspace_name_indexes_index_name_documents_query_post: Optional[List[components_deepsetclouddocument.DeepsetCloudDocument]] = dataclasses.field(default=None)
    r"""Successful Response"""
    

