"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import httpvalidationerror as shared_httpvalidationerror
from typing import Any, Optional



@dataclasses.dataclass
class RemoveTokenAPIV1TokenAPITokenIDDeleteRequest:
    api_token_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'api_token_id', 'style': 'simple', 'explode': False }})
    r"""A unique identifier of the API token that you want to remove. You can run the Get Tokens endpoint to check the IDs of the existing API tokens."""
    




@dataclasses.dataclass
class RemoveTokenAPIV1TokenAPITokenIDDeleteResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    remove_token_api_v1_token_api_token_id_delete_200_application_json_any: Optional[Any] = dataclasses.field(default=None)
    r"""Successful Response"""
    

