"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import httpvalidationerror as shared_httpvalidationerror
from enum import Enum
from typing import Any, Optional

class RemoveTokenAPIV1ModelRegistryTokensProviderDeleteProviderModelProvider(str, Enum):
    r"""The provider of the model registry"""
    HUGGINGFACE = 'huggingface'
    OPENAI = 'openai'
    COHERE = 'cohere'



@dataclasses.dataclass
class RemoveTokenAPIV1ModelRegistryTokensProviderDeleteRequest:
    provider: RemoveTokenAPIV1ModelRegistryTokensProviderDeleteProviderModelProvider = dataclasses.field(metadata={'path_param': { 'field_name': 'provider', 'style': 'simple', 'explode': False }})
    r"""The provider of the model registry"""
    




@dataclasses.dataclass
class RemoveTokenAPIV1ModelRegistryTokensProviderDeleteResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    http_validation_error: Optional[shared_httpvalidationerror.HTTPValidationError] = dataclasses.field(default=None)
    r"""Validation Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    remove_token_api_v1_model_registry_tokens_provider_delete_202_application_json_any: Optional[Any] = dataclasses.field(default=None)
    r"""Successful Response"""
    

