"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import pipelinequery as components_pipelinequery
from ...models.components import searchresult as components_searchresult
from typing import Optional


@dataclasses.dataclass
class SearchAPIV1WorkspacesWorkspaceNamePipelinesPipelineNameSearchPostRequest:
    pipeline_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'pipeline_name', 'style': 'simple', 'explode': False }})
    r"""The name of the pipeline that you want to use for search."""
    pipeline_query: components_pipelinequery.PipelineQuery = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    workspace_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspace_name', 'style': 'simple', 'explode': False }})
    r"""Type the name of the workspace."""
    



@dataclasses.dataclass
class SearchAPIV1WorkspacesWorkspaceNamePipelinesPipelineNameSearchPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    search_result: Optional[components_searchresult.SearchResult] = dataclasses.field(default=None)
    r"""Returns the search results."""
    

