"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import deepsetcloudanswer as shared_deepsetcloudanswer
from ..shared import deepsetclouddocument as shared_deepsetclouddocument
from dataclasses_json import Undefined, dataclass_json
from deepset_cloud import utils
from typing import Any, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeepsetCloudQueryResponse:
    
    query: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('query') }})
    r"""The search query"""
    debug: Optional[dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('_debug'), 'exclude': lambda f: f is None }})
    answers: Optional[list[shared_deepsetcloudanswer.DeepsetCloudAnswer]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('answers'), 'exclude': lambda f: f is None }})
    r"""List of deepset Cloud answers."""
    documents: Optional[list[shared_deepsetclouddocument.DeepsetCloudDocument]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('documents'), 'exclude': lambda f: f is None }})
    r"""List of deepset Cloud documents."""
    query_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('query_id'), 'exclude': lambda f: f is None }})
    r"""Unique identifier of the search query."""
    