"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ServerState(str, Enum):
    r"""An enumeration."""
    STARTING = 'STARTING'
    UP = 'UP'
    DOWN = 'DOWN'
