"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ServerType(str, Enum):
    r"""An enumeration."""
    CPU_SERVER = 'cpu-server'
    GPU_SERVER = 'gpu-server'
    UNKNOWN = 'unknown'
