"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import serverstate_enum as shared_serverstate_enum
from ..shared import servertype_enum as shared_servertype_enum
from dataclasses_json import Undefined, dataclass_json
from deepset_cloud import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Server:
    r"""Successful Response"""
    
    server_type: shared_servertype_enum.ServerTypeEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('server_type') }})
    r"""An enumeration."""
    state: shared_serverstate_enum.ServerStateEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('state') }})
    r"""An enumeration."""
    